### ISSUE TITLE
Failed to get cargo metadata

### ISSUE THREAD

**Issue by Comradin** [mettke/ticket-printer#1]
When starting the application with a non-existing parameter I get the following error message:

```
$ ./ticket_printer --create-config
Error: Could not load configuration
Info: caused by Failed to get cargo metadata.
```

I assume this is due to the missing config file?

**Comment by mettke** [comment]
Unfortunately this is not due to a missing config file. I had a look at it and it seems that `confy` (my current configuration library) requires the `Cargo.toml` to be next to the binary. I don't like that so the upcoming Version 1.1.0 will switch to the `config` library.
