### ISSUE TITLE
Config file format kind of undocumented

### ISSUE THREAD

**Issue by Comradin** [mettke/ticket-printer#2]
Please add an example config toml for a more simple configuration.

This should be way more easy than skimming the code for the config struct definitions read from the toml file.

**Comment by mettke** [comment]
There are example configurations in the `README.md` and below the `config` folder. 

Still the upcoming release 1.1.0 will introduce new configuration formats (namely yaml and json) and add new configuration folders (`/etc/ticket_printer/ticket_printer.{ext}` and `./ticket_printer.{ext}`)
