### ISSUE TITLE
Failed to print generated pdf

### ISSUE THREAD

**Issue by Comradin** [mettke/ticket-printer#4]
The print fails due to a, what it looks like, race condition between printing the generated pdf document and the cleanup process, that does the housekeeping.

```
usr/bin/lp: Error - unable to access ""/tmp/.tmpMQ6eMr/12128.pdf"" - No such file or directory
Error: Unable to print ticket

```

**Comment by Comradin** [comment]
Misleading interpretation, looks like a broken path due to double double-quotes instead?

**Comment by mettke** [comment]
Yeah, I have to improve the path handling when calling the external lp command. Will be fixed with the next version.
